services:
  - type: web
    name: vue-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: "https://your-django-backend.onrender.com"
