services:
  - type: web
    name: django-backend
    env: python
    plan: free
    # Вариант 1: С build.sh
    buildCommand: "cd backend && ./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    
    # Вариант 2: Без build.sh (раскомментируйте если хотите использовать)
    # buildCommand: "pip install -r backend/requirements.txt && cd backend && python manage.py collectstatic --no-input && python manage.py migrate"
    # startCommand: "cd backend && gunicorn config.wsgi:application"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DB_ENGINE
        value: "django.db.backends.postgresql"
      - key: DB_NAME
        fromDatabase:
          name: postgres-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: postgres-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: postgres-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: postgres-db
          property: port

databases:
  - name: postgres-db
    databaseName: djangodb
    user: djangouser
    plan: free
