# Generated by Django 5.2.5 on 2025-08-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_add_slug_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RossiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Шаблон Rossi',
                'verbose_name_plural': 'Шаблоны Rossi',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='gutierreztemplate',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
